In [1]:
import numpy

In [2]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter = ',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [3]:
data = numpy.loadtxt(fname="inflammation-01.csv", delimiter = ',')
print(data)
print(type(data))

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]
<class 'numpy.ndarray'>


In [4]:
print(data.dtype)
print(data.shape)

float64
(60, 40)


In [5]:
print("First value in data:", data[0,0])
print("MIddle value in data:", data[30,20])

First value in data: 0.0
MIddle value in data: 13.0
